### ISSUE TITLE
Draft with content into the datastore. Is it normal?

### ISSUE THREAD

**Issue by dioclecio** [elliott5/tiddly#3]
Dear Prof. Elliott,

I made a test with your tiddly-master and saw a peculiar activity.

When I add a Tiddler, it goes to the datastore with content and some "Draft ..." tiddlers registered.

But, when I remove this particular Tiddler from the Tiddlywiki platform, It remais empty into the datastore. But the other Draft tiddlers remains with content. I dont see them into my tiddly. But it is strange to see them into the datastore.

![consulta_do_armazenamento_de_dados_-_c0nt4t0s3t433f4s](https://user-images.githubusercontent.com/1454277/28942156-b0955768-7870-11e7-89ca-395e6d7052f9.png)

Is it normal?

Sincerely yours,

Dino

**Comment by elliott5** [comment]
Yes Dino, this is how it is written, originally because of saving a history of all changes (which is now off by default).

Lines 302 onwards are where in the code to look.

It could easily be changed to do a delete() call, rather than a put() call of blank data if the WriteTiddlerHistory bool is not set.
